# Configuration file for Beckhoff EL7031
vendor_id: 0x00000002
product_id: 0x1b773052
sdo:  # sdo data to be transferred at drive startup
  - {index: 0x8012, sub_index: 1, type: bool, value: 1} #Operation mode set to direct velocity
rpdo:  # RxPDO
  - index: 0x1600
    channels:
      - {index: 0x0000, sub_index: 0x00, type: bool} # Gap
      - {index: 0x7000, sub_index: 0x02, type: bool} # Enable latch extern on positive edge
      - {index: 0x7000, sub_index: 0x03, type: bool} # Set counter
      - {index: 0x7000, sub_index: 0x04, type: bool} # Enable latch extern on negative edge
      - {index: 0x0000, sub_index: 0x00, type: bit4} # Gap
      - {index: 0x0000, sub_index: 0x00, type: bit8} # Gap
      - {index: 0x7000, sub_index: 0x11, type: int16} # Set counter value
  - index: 0x1602
    channels:
      - {index: 0x7010, sub_index: 0x01, type: bool, mask: 1, command_interface: enable} # Enable
      - {index: 0x7010, sub_index: 0x02, type: bool, mask: 2, command_interface: reset} # Reset
      - {index: 0x7010, sub_index: 0x03, type: bool} # Reduce torque
      - {index: 0x0000, sub_index: 0x00, type: bit5} # Gap
      - {index: 0x0000, sub_index: 0x00, type: bit8} # Gap
  - index: 0x1604
    channels:
      - {index: 0x7010, sub_index: 0x21, type: int16, command_interface: velocity} # Velocity
tpdo:  # TxPDO
  - index: 0x1a03
    channels:
      - {index: 0x6010, sub_index: 0x01, type: bool, mask: 1, state_interface: ready_to_enable} # Ready to enable
      - {index: 0x6010, sub_index: 0x02, type: bool, mask: 2, state_interface: ready} # Ready
      - {index: 0x6010, sub_index: 0x03, type: bool, mask: 4, state_interface: warning} # Warning
      - {index: 0x6010, sub_index: 0x04, type: bool, mask: 8, state_interface: error} # Error
      - {index: 0x6010, sub_index: 0x05, type: bool} # Moving positive
      - {index: 0x6010, sub_index: 0x06, type: bool} # Moving negative
      - {index: 0x6010, sub_index: 0x07, type: bool} # Torque reduced
      - {index: 0x0000, sub_index: 0x00, type: bool} # Gap
      - {index: 0x0000, sub_index: 0x00, type: bit3} # Gap
      - {index: 0x6010, sub_index: 0x0C, type: bool} # Digital input 1
      - {index: 0x6010, sub_index: 0x0D, type: bool} # Digital input 2
      - {index: 0x6010, sub_index: 0x0E, type: bool} # Sync error
      - {index: 0x0000, sub_index: 0x00, type: bool} # Gap
      - {index: 0x6010, sub_index: 0x10, type: bool} # TxPDO Toggle
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: disable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}
